GLOBALS:

  input-worksheet: "IMMISSIONE DATI"
  product-column: "I"
  starting-row: 64
  ending-row: 79
  buyer:
    column: "F"
    full-name-row: 11
    address-row: 12
    floor-row: 13
    city-row: 14
    telephone-row: 15
    cellphone-row: 16
    email-row: 18
  available-bar-worksheet: "Barre"
  pieces-column: "C"
  width-column: "B"
  starting-row-bar: 7
  ending-row-bar: 74
  default-bar-length: 6000
  info-worksheet: "tmp"
  order-id-position: "C4"
  client-id-position: "C20"

CLOSE:
  worksheet: "prod CLOSE"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 8
  ending-row: 23

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "CLOSE"
      refinement-column: "CM"
      quantity-column: "CI"
      length-column: "CJ"
      command-verse: "CP"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"
      machinings:
        - code: "CERNIERA FORI ANTA"
          starting-column: "DW"
          ending-column: "EB"
        - code: "FORO SCASSI TELAIO"
          starting-column: "ED"
          ending-column: "EF"

    - code: "CANALINO VERTICALE"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "CR"
      length-column: "CS"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO VERTICALE"

    - code: "CANALINO ORIZZONTALE"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "CV"
      length-column: "CW"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO ORIZZONTALE"

    - code: "MONTANTE SX"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "DA"
      length-column: "DB"
      left-angle-cut: 90
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE SX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "TRAVERSO SUPERIORE"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "DE"
      length-column: "DF"
      left-angle-cut: 45
      right-angle-cut: 90
      height: 200
      bar-code: "TRAVERSO SUPERIORE"

    - code: "MONTANTE DX"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "DI"
      length-column: "DJ"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE DX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "PROFILO SOGLIA"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "DM"
      length-column: "DN"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO SOGLIA"

MODERNA:
  worksheet: "prod MODERNA"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 8
  ending-row: 23

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "MODERNA"
      quantity-column: "CI"
      length-column: "CJ"
      command-verse: "CP"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"
      machinings:
        - code: "FORO DOGA"
        - code: "FORO DOGA"
        - code: "FORO DOGA"
        - code: "FORO DOGA"

    - code: "CERNIERA TUBOLARE"
      brand: "PELLEGRINO"
      system: "MODERNA"
      quantity-column: "CR"
      length-column: "CS"
      in-stock-column: "CQ"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "CERNIERA TUBOLARE"
      machinings:
        - code: "MACHINING CERNIERA TUBOLARE"

    - code: "CERNIERA APERTA"
      brand: "PELLEGRINO"
      system: "MODERNA"
      quantity-column: "EL"
      length-column: "EM"
      in-stock-column: "CU"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "CERNIERA APERTA"
      machinings:
        - code: "MACHINING CERNIERA APERTA"

    - code: "PROFILO GANCIO-UNCINO"
      brand: "PELLEGRINO"
      system: "MODERNA"
      quantity-column: "EO"
      length-column: "EM"
      in-stock-column: "EN"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO GANCIO-UNCINO"

    - code: "H"
      brand: "PELLEGRINO"
      system: "MODERNA"
      quantity-column: "ER"
      length-column: "ES"
      in-stock-column: "EQ"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "H"
      machinings:
        - code: "MACHINING H"

CLICK_RAPID:
  worksheet: "prod CLICK_RAPID"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 8
  ending-row: 23

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "CLICK_RAPID"
      quantity-column: "CI"
      length-column: "CJ"
      command-verse: "CP"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"
      machinings:
        - code: "LAVORAZIONE SUPERIORE"
        - code: "LAVORAZIONE INFERIORE"
        - code: "FORO CHIAVISTELLO VERTICALE"
          offset-column: "FB"
          quantity-column: "EZ"


    - code: "CANALINO VERTICALE"
      brand: "PELLEGRINO"
      system: "CLICK_RAPID"
      quantity-column: "CR"
      length-column: "CS"
      in-stock-column: "CQ"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO VERTICALE"

    - code: "PROFILO DI TENUTA LATERALE"
      brand: "PELLEGRINO"
      system: "CLICK_RAPID"
      quantity-column: "EU"
      length-column: "EX"
      in-stock-column: "ET"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DI TENUTA LATERALE"

MODU:
  worksheet: "prod MODU"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 6
  ending-row: 22

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "MODU"
      quantity-column: "AU"
      length-column: "AV"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"

    - code: "TAGLIO GUIDA"
      brand: "PELLEGRINO"
      system: "MODU"
      quantity-column: "BB"
      length-column: "BC"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "TAGLIO GUIDA"
      machinings:
        - code: "PEZZO DX"
        - code: "PEZZO SX"

MODI:
  worksheet: "prod MODI"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 8
  ending-row: 22

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "MODI"
      quantity-column: "CI"
      length-column: "CJ"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"

    - code: "TAGLIO GUIDA"
      brand: "PELLEGRINO"
      system: "MODI"
      quantity-column: "EU"
      length-column: "EX"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "TAGLIO GUIDA"
      machinings:
        - code: "PEZZO DX"
        - code: "PEZZO SX"

FULL_D:
  worksheet: "prod FULL_D"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 8
  ending-row: 22

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "FULL_D"
      refinement-column: "CM"
      quantity-column: "CI"
      length-column: "CJ"
      command-verse: "CP"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"
      machinings:
        - code: "CERNIERA FORI ANTA"
          starting-column: "DW"
          ending-column: "EB"
        - code: "FORO SCASSI TELAIO"
          starting-column: "ED"
          ending-column: "EF"

    - code: "CANALINO VERTICALE"
      brand: "PELLEGRINO"
      system: "FULL_D"
      quantity-column: "CR"
      length-column: "CS"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO VERTICALE"

    - code: "CANALINO ORIZZONTALE"
      brand: "PELLEGRINO"
      system: "FULL_D"
      quantity-column: "CV"
      length-column: "CW"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO ORIZZONTALE"

    - code: "MONTANTE SX"
      brand: "PELLEGRINO"
      system: "FULL_D"
      quantity-column: "DA"
      length-column: "DB"
      left-angle-cut: 90
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE SX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "TRAVERSO SUPERIORE"
      brand: "PELLEGRINO"
      system: "FULL_D"
      quantity-column: "DE"
      length-column: "DF"
      left-angle-cut: 45
      right-angle-cut: 90
      height: 200
      bar-code: "TRAVERSO SUPERIORE"

    - code: "MONTANTE DX"
      brand: "PELLEGRINO"
      system: "FULL_D"
      quantity-column: "DI"
      length-column: "DJ"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE DX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "PROFILO SOGLIA"
      brand: "PELLEGRINO"
      system: "FULL_D"
      quantity-column: "DM"
      length-column: "DN"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO SOGLIA"

FULL_W:
  worksheet: "prod FULL_W"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 8
  ending-row: 22

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "FULL_W"
      refinement-column: "CM"
      quantity-column: "CI"
      length-column: "CJ"
      command-verse: "CP"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"
      machinings:
        - code: "CERNIERA FORI ANTA"
          starting-column: "DW"
          ending-column: "EB"
        - code: "FORO SCASSI TELAIO"
          starting-column: "ED"
          ending-column: "EF"

    - code: "CANALINO VERTICALE"
      brand: "PELLEGRINO"
      system: "FULL_W"
      quantity-column: "CR"
      length-column: "CS"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO VERTICALE"

    - code: "CANALINO ORIZZONTALE"
      brand: "PELLEGRINO"
      system: "FULL_W"
      quantity-column: "CV"
      length-column: "CW"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO ORIZZONTALE"

    - code: "MONTANTE SX"
      brand: "PELLEGRINO"
      system: "FULL_W"
      quantity-column: "DA"
      length-column: "DB"
      left-angle-cut: 90
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE SX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "TRAVERSO SUPERIORE"
      brand: "PELLEGRINO"
      system: "FULL_W"
      quantity-column: "DE"
      length-column: "DF"
      left-angle-cut: 45
      right-angle-cut: 90
      height: 200
      bar-code: "TRAVERSO SUPERIORE"

    - code: "MONTANTE DX"
      brand: "PELLEGRINO"
      system: "FULL_W"
      quantity-column: "DI"
      length-column: "DJ"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE DX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "PROFILO SOGLIA"
      brand: "PELLEGRINO"
      system: "FULL_W"
      quantity-column: "DM"
      length-column: "DN"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO SOGLIA"

FULL_G:
  worksheet: "prod FULL_G"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 8
  ending-row: 22

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "FULL_G"
      refinement-column: "CM"
      quantity-column: "CI"
      length-column: "CJ"
      command-verse: "CP"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"
      machinings:
        - code: "CERNIERA FORI ANTA"
          starting-column: "DW"
          ending-column: "EB"
        - code: "FORO SCASSI TELAIO"
          starting-column: "ED"
          ending-column: "EF"

    - code: "CANALINO VERTICALE"
      brand: "PELLEGRINO"
      system: "FULL_G"
      quantity-column: "CR"
      length-column: "CS"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO VERTICALE"

    - code: "CANALINO ORIZZONTALE"
      brand: "PELLEGRINO"
      system: "FULL_G"
      quantity-column: "CV"
      length-column: "CW"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO ORIZZONTALE"

    - code: "MONTANTE SX"
      brand: "PELLEGRINO"
      system: "FULL_G"
      quantity-column: "DA"
      length-column: "DB"
      left-angle-cut: 90
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE SX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "TRAVERSO SUPERIORE"
      brand: "PELLEGRINO"
      system: "FULL_G"
      quantity-column: "DE"
      length-column: "DF"
      left-angle-cut: 45
      right-angle-cut: 90
      height: 200
      bar-code: "TRAVERSO SUPERIORE"

    - code: "MONTANTE DX"
      brand: "PELLEGRINO"
      system: "FULL_G"
      quantity-column: "DI"
      length-column: "DJ"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE DX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "PROFILO SOGLIA"
      brand: "PELLEGRINO"
      system: "FULL_G"
      quantity-column: "DM"
      length-column: "DN"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO SOGLIA"

GATE:
  worksheet: "prod GATE"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 8
  ending-row: 23

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "GATE"
      quantity-column: "CI"
      length-column: "CJ"
      command-verse: "CP"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"
      machinings:
        - code: "CERNIERA FORI ANTA"
          starting-column: "DW"
          ending-column: "EB"
        - code: "FORO SCASSI TELAIO"
          starting-column: "ED"
          ending-column: "EF"

    - code: "CANALINO VERTICALE"
      brand: "PELLEGRINO"
      system: "GATE"
      quantity-column: "CR"
      length-column: "CS"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO VERTICALE"

    - code: "CANALINO ORIZZONTALE"
      brand: "PELLEGRINO"
      system: "GATE"
      quantity-column: "CV"
      length-column: "CW"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO ORIZZONTALE"

    - code: "MONTANTE SX"
      brand: "PELLEGRINO"
      system: "GATE"
      quantity-column: "DA"
      length-column: "DB"
      left-angle-cut: 90
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE SX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "TRAVERSO SUPERIORE"
      brand: "PELLEGRINO"
      system: "GATE"
      quantity-column: "DE"
      length-column: "DF"
      left-angle-cut: 45
      right-angle-cut: 90
      height: 200
      bar-code: "TRAVERSO SUPERIORE"

    - code: "MONTANTE DX"
      brand: "PELLEGRINO"
      system: "GATE"
      quantity-column: "DI"
      length-column: "DJ"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE DX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "PROFILO SOGLIA"
      brand: "PELLEGRINO"
      system: "GATE"
      quantity-column: "DM"
      length-column: "DN"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO SOGLIA"


