GLOBALS:

  input-worksheet: "IMMISSIONE DATI"
  product-column: "I"
  starting-row: 64
  ending-row: 79
  buyer:
    column: "F"
    full-name-row: 11
    address-row: 12
    floor-row: 13
    city-row: 14
    telephone-row: 15
    cellphone-row: 16
    email-row: 18
  available-bar-worksheet: "Barre"
  pieces-column: "C"
  width-column: "B"
  starting-row-bar: 7
  ending-row-bar: 74
  default-bar-length: 6000

CLOSE:
  worksheet: "prod CLOSE"
  product-column: "C"
  pieces-column: "D"
  width-column: "E"
  height-column: "F"
  starting-row: 8
  ending-row: 23

  profiles:
    - code: "PROFILO DOGA"
      brand: "PELLEGRINO"
      system: "CLOSE"
      refinement-column: "CM"
      quantity-column: "CI"
      length-column: "CJ"
      command-verse: "CP"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO DOGA"
      machinings:
        - code: "CERNIERA FORI ANTA"
          starting-column: "DW"
          ending-column: "EB"
        - code: "FORO SCASSI TELAIO"
          starting-column: "ED"
          ending-column: "EF"

    - code: "CANALINO VERTICALE"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "CR"
      length-column: "CS"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO VERTICALE"

    - code: "CANALINO ORIZZONTALE"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "CV"
      length-column: "CW"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "CANALINO ORIZZONTALE"

    - code: "MONTANTE SX"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "DA"
      length-column: "DB"
      left-angle-cut: 90
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE SX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "TRAVERSO SUPERIORE"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "DE"
      length-column: "DF"
      left-angle-cut: 45
      right-angle-cut: 90
      height: 200
      bar-code: "TRAVERSO SUPERIORE"

    - code: "MONTANTE DX"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "DI"
      length-column: "DJ"
      left-angle-cut: 45
      right-angle-cut: 45
      height: 200
      bar-code: "MONTANTE DX"
      machinings:
        - code: "FORO FISSAGGIO"
          starting-column: "DQ"
          ending-column: "DU"

    - code: "PROFILO SOGLIA"
      brand: "PELLEGRINO"
      system: "CLOSE"
      quantity-column: "DM"
      length-column: "DN"
      left-angle-cut: 90
      right-angle-cut: 90
      height: 200
      bar-code: "PROFILO SOGLIA"

