name: docs
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Generate Documentation
        run: |
          mkdir -p ./docs
          pdoc --html p2k2_converter --output-dir ./docs --force

      - name: ls
        run: ls -la ./docs

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          publish_branch: docs
          publish_dir: ./docs

